# Generated by Django 2.1.2 on 2018-10-09 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro', models.IntegerField()),
                ('km', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Competidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barco', models.CharField(max_length=30)),
                ('club', models.CharField(max_length=30)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competidores', related_query_name='competidor', to='inet.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', related_query_name='participante', to='inet.Competidor')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_vuelta', models.IntegerField()),
                ('hora', models.TimeField()),
                ('velocidad', models.FloatField()),
                ('boya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros', related_query_name='registro', to='inet.Boya')),
                ('competidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', related_query_name='registro', to='inet.Competidor')),
            ],
        ),
        migrations.AddField(
            model_name='boya',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boyas', related_query_name='boya', to='inet.Categoria'),
        ),
    ]
